- name: testing of purge
  hosts: localhost
  force_handlers: yes
  vars:
   window: 0.1
   start_time: "{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch) }}"
   end_time: "{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch | int + 600) }}"
   iter_end: "{{ (window  * 60 / 2) | int}}"

  tasks:
  
   - name: generating client list
     shell: echo "A B C D"
     register: client

   - block:
      - debug:
         msg: "No client list found, thus existing job"

      - meta: end_play
     when: (client.stdout is not defined) or (client.stdout |length == 0)

   - debug:
        #var: client_list
      var: iter_end
   - debug:
      var: client.stdout
      
   - include_tasks: invoke_purge.yml
     #register: result
     loop: "{{ range(1, (iter_end)|int + 1  ,1) | list}}"
     loop_control:
    #     pause: 5
      loop_var: iteration

   - include_tasks: post_purge.yml

